from ansys.meshing.prime.autogen.primeconfig import *
from ansys.meshing.prime.autogen.commontypes import *
from ansys.meshing.prime.autogen.fileiostructs import *
from ansys.meshing.prime.autogen.controlstructs import *
from ansys.meshing.prime.autogen.modelstructs import *
from ansys.meshing.prime.autogen.partstructs import *
from ansys.meshing.prime.autogen.surfacesearchstructs import *
from ansys.meshing.prime.autogen.surferstructs import *
from ansys.meshing.prime.autogen.igastructs import *
from ansys.meshing.prime.autogen.sizecontrolstructs import *
from ansys.meshing.prime.autogen.sizefieldstructs import *
from ansys.meshing.prime.autogen.meshinfostructs import *
