name: Nightly Documentation Build

on:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  nightly_docs_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # used for documentation deployment
      - name: Get Bot Application Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.BOT_APPLICATION_PRIVATE_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install ansys-meshing-prime
        run: |
          python -m pip install --upgrade pip
          pip install . --find-links deps
          xvfb-run python -c "import ansys.meshing.prime; print('Import successful')"
      
      - name: Build Documentation
        run: |
          pip install -r requirements_docs.txt
          xvfb-run make -C doc html SPHINXOPTS="-W"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          repository-name: pyansys/pyprime-dev-docs
          token: ${{ steps.get_workflow_token.outputs.token }}
          branch: gh-pages
          folder: doc/build/html
          clean: true

      # - name: Notify if fail
      #   uses: skitionek/notify-microsoft-teams@master
      #   if: ${{ failure() }}
      #   with:
      #     webhook_url: ${{ secrets.TEAM_HOOK }}
      #     needs: ${{ toJson(needs) }}
      #     job: ${{ toJson(job) }}
      #     steps: ${{ toJson(steps) }}
      #     overwrite: "{
      #       title: `${workflow} failed.`, 
      #       }"
